package com.example.jobportal.model.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_UPDATE,
    JOB_EXPIRED,
    JOB_CREATED,
    JOB_UPDATED,
    JOB_STATUS_CHANGED,
    JOB_PUBLISHED,
    JOB_SAVED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    COMPANY_VERIFY_REQUESTED,
    COMPANY_VERIFIED,
    COMPANY_REJECTED,
    COMPANY_STATUS_CHANGED,
    RESUME_CREATED,
    RESUME_UPDATED,
    RESUME_DELETED,
    RESUME_PRIMARY_CHANGED,
    RESUME_VISIBILITY_CHANGED,
    SYSTEM
}
